// Generated by CoffeeScript 1.4.0
var app;

app = angular.module('WillowApp', []);

app.value('directions', ['North', 'Northeast', 'East', 'Southeast', 'South', 'Southwest', 'West', 'Northwest']);

app.controller('WillowCtrl', function($scope, directions) {
  $scope.branchTtl = 100;
  $scope.logarithmic = function(value) {
    return Math.floor(Math.pow(10, value));
  };
  $scope.directional = function(value) {
    return directions[value];
  };
  return $scope.unchanged = function(a) {
    return a;
  };
});

app.directive('slider', function() {
  return {
    restrict: 'E',
    replace: true,
    scope: {
      text: '@',
      id: '@',
      min: '@',
      max: '@',
      step: '@',
      model: '=',
      convertValue: '=',
      displayValue: '='
    },
    template: "<div id=\"{{id}}Control\" class=\"control\">\n   {{text}}: <span id=\"{{id}}Text\" class=\"text\">{{displayText}}</span><br/>\n   <div class=\"slider\">\n     <div id=\"{{id}}Slide\"></div>\n   </div>\n   <input type=\"text\" id=\"{{id}}\" class=\"model\" value=\"{{model}}\" size=\"4\"/>\n</div>",
    link: function(scope, elem, attrs) {
      var display;
      display = function() {
        return scope.displayText = scope.displayValue(scope.model);
      };
      return (elem.find('.slider div:first')).slider({
        min: attrs.min,
        max: attrs.max,
        value: scope.model,
        step: scope.step,
        slide: function(event, ui) {
          return scope.$apply(function() {
            scope.model = scope.convertValue(ui.value);
            return display();
          });
        }
      });
    }
  };
});
