// Generated by CoffeeScript 1.4.0
var DirectionFunctions;

DirectionFunctions = {
  random: function() {
    return function(point, grid) {
      return Math.floor(Math.random() * 8);
    };
  },
  favorDirection: function(dir, weight) {
    return function(point, grid) {
      if (Math.random() < weight) {
        return dir;
      } else {
        return Math.floor(Math.random() * 8);
      }
    };
  },
  trendToCenter: function(weight) {
    return function(point, grid) {
      if (Math.random() < weight) {
        return point.getDirectionTo(grid.center);
      } else {
        return Math.floor(Math.random() * 8);
      }
    };
  },
  star: function(weight) {
    return function(point, grid) {
      return Math.random() * 8;
    };
  },
  bounce: function(startDir, weight) {
    return function(point, grid) {
      return Math.random() * 8;
    };
  }
};
