// Generated by CoffeeScript 1.4.0
var Point,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Point = (function() {

  function Point(x, y, grid) {
    this.grid = grid;
    this.wouldIntersect = __bind(this.wouldIntersect, this);

    this.neighborAt = __bind(this.neighborAt, this);

    this.directionTo = __bind(this.directionTo, this);

    this.openNeighbors = __bind(this.openNeighbors, this);

    this.neighborIsOpen = __bind(this.neighborIsOpen, this);

    this.neighbors = __bind(this.neighbors, this);

    this.branchable = __bind(this.branchable, this);

    this.toString = __bind(this.toString, this);

    this.x = parseInt(x);
    this.y = parseInt(y);
    this.realX = this.x * this.grid.cellSize + 1;
    this.realY = this.y * this.grid.cellSize + 1;
    this.connections = new Set();
  }

  Point.prototype.toString = function() {
    return this.x + '/' + this.y;
  };

  Point.prototype.branchable = function() {
    return !this.grid.hasSurrounded(this);
  };

  Point.prototype.neighbors = function() {
    var dir;
    return new Set((function() {
      var _i, _results;
      _results = [];
      for (dir = _i = 0; _i <= 7; dir = ++_i) {
        _results.push(this.neighborAt(dir));
      }
      return _results;
    }).call(this));
  };

  Point.prototype.neighborIsOpen = function(p) {
    return (p != null) && !this.grid.hasDrawn(p) && !this.grid.hasSurrounded(p) && !this.wouldIntersect(p);
  };

  Point.prototype.openNeighbors = function() {
    var _this = this;
    return this.neighbors().filter(function(p) {
      return _this.neighborIsOpen(p);
    });
  };

  Point.prototype.directionTo = function(dest) {
    if (!(dest != null)) {
      return null;
    }
    if (this.x === dest.x && this.y > dest.y) {
      return 0;
    }
    if (this.x < dest.x && this.y > dest.y) {
      return 1;
    }
    if (this.x < dest.x && this.y === dest.y) {
      return 2;
    }
    if (this.x < dest.x && this.y < dest.y) {
      return 3;
    }
    if (this.x === dest.x && this.y < dest.y) {
      return 4;
    }
    if (this.x > dest.x && this.y < dest.y) {
      return 5;
    }
    if (this.x > dest.x && this.y === dest.y) {
      return 6;
    }
    if (this.x > dest.x && this.y > dest.y) {
      return 7;
    }
    throw "Can't find direction from " + this.x + "/" + this.y + " to " + dest.toString();
  };

  Point.prototype.neighborAt = function(dir) {
    var _base, _base1, _base2, _base3, _base4, _base5, _base6, _base7;
    if (!(dir != null)) {
      return null;
    }
    switch (dir) {
      case 0:
        if (this.y > 0) {
          return (_base = this.neighbors)[0] || (_base[0] = this.grid.point(this.x, this.y - 1));
        }
        break;
      case 1:
        if (this.x < this.grid.width && this.y > 0) {
          return (_base1 = this.neighbors)[1] || (_base1[1] = this.grid.point(this.x + 1, this.y - 1));
        }
        break;
      case 2:
        if (this.x < this.grid.width) {
          return (_base2 = this.neighbors)[2] || (_base2[2] = this.grid.point(this.x + 1, this.y));
        }
        break;
      case 3:
        if (this.x < this.grid.width && this.y < this.grid.height) {
          return (_base3 = this.neighbors)[3] || (_base3[3] = this.grid.point(this.x + 1, this.y + 1));
        }
        break;
      case 4:
        if (this.y < this.grid.height) {
          return (_base4 = this.neighbors)[4] || (_base4[4] = this.grid.point(this.x, this.y + 1));
        }
        break;
      case 5:
        if (this.x > 0 && this.y < this.grid.height) {
          return (_base5 = this.neighbors)[5] || (_base5[5] = this.grid.point(this.x - 1, this.y + 1));
        }
        break;
      case 6:
        if (this.x > 0) {
          return (_base6 = this.neighbors)[6] || (_base6[6] = this.grid.point(this.x - 1, this.y));
        }
        break;
      case 7:
        if (this.x > 0 && this.y > 0) {
          return (_base7 = this.neighbors)[7] || (_base7[7] = this.grid.point(this.x - 1, this.y - 1));
        }
    }
    return null;
  };

  Point.prototype.wouldIntersect = function(dest, dir) {
    var intersector1, intersector2;
    if (dir == null) {
      dir = null;
    }
    if (!(dir != null)) {
      dir = this.directionTo(dest);
    }
    if (dir % 2 !== 1) {
      return false;
    }
    intersector1 = this.neighborAt((dir + 1) % 8);
    intersector2 = this.neighborAt((dir - 1) % 8);
    return (intersector1 != null ? intersector1.connections.contains(intersector2) : void 0) || (intersector2 != null ? intersector2.connections.contains(intersector1) : void 0);
  };

  return Point;

})();
