// Generated by CoffeeScript 1.6.2
describe("Point", function() {
  beforeEach(function() {
    var canvas, context, g;

    context = {
      lineWidth: 10,
      strokeStyle: '',
      beginPath: function() {},
      moveTo: function(x, y) {},
      lineTo: function(x, y) {},
      closePath: function() {},
      stroke: function() {},
      clearRect: function() {}
    };
    canvas = {
      width: 100,
      height: 100,
      getContext: function() {
        return context;
      }
    };
    g = new Grid(canvas);
    g.init({
      directionStyle: 'random',
      branchStyle: 'random',
      cellSize: 10
    });
    this.p33 = g.point(3, 3);
    this.p34 = g.point(3, 4);
    this.p35 = g.point(3, 5);
    this.p43 = g.point(4, 3);
    this.p44 = g.point(4, 4);
    this.p45 = g.point(4, 5);
    this.p53 = g.point(5, 3);
    this.p54 = g.point(5, 4);
    return this.p55 = g.point(5, 5);
  });
  it('toStrings', function() {
    return expect(this.p33.toString()).toEqual('3/3');
  });
  it('finds neighbors by direction', function() {
    var p;

    p = this.p44.neighborAt(0);
    expect(p.x).toEqual(4);
    expect(p.y).toEqual(3);
    p = this.p44.neighborAt(1);
    expect(p.x).toEqual(5);
    expect(p.y).toEqual(3);
    p = this.p44.neighborAt(2);
    expect(p.x).toEqual(5);
    expect(p.y).toEqual(4);
    p = this.p44.neighborAt(3);
    expect(p.x).toEqual(5);
    expect(p.y).toEqual(5);
    p = this.p44.neighborAt(4);
    expect(p.x).toEqual(4);
    expect(p.y).toEqual(5);
    p = this.p44.neighborAt(5);
    expect(p.x).toEqual(3);
    expect(p.y).toEqual(5);
    p = this.p44.neighborAt(6);
    expect(p.x).toEqual(3);
    expect(p.y).toEqual(4);
    p = this.p44.neighborAt(7);
    expect(p.x).toEqual(3);
    expect(p.y).toEqual(3);
    return expect(this.p44.neighbors().length()).toEqual(8);
  });
  return it('finds directions to neighbors', function() {
    expect(this.p44.directionTo(this.p43)).toEqual(0);
    expect(this.p44.directionTo(this.p53)).toEqual(1);
    expect(this.p44.directionTo(this.p54)).toEqual(2);
    expect(this.p44.directionTo(this.p55)).toEqual(3);
    expect(this.p44.directionTo(this.p45)).toEqual(4);
    expect(this.p44.directionTo(this.p35)).toEqual(5);
    expect(this.p44.directionTo(this.p34)).toEqual(6);
    return expect(this.p44.directionTo(this.p33)).toEqual(7);
  });
});
