// Generated by CoffeeScript 1.4.0

describe("Set", function() {
  beforeEach(function() {
    return this.s = new Set();
  });
  return it('should add elements', function() {
    this.s.add(1);
    return expect(this.s.contains(1)).toEqual(true);
  });
});
